services:
  - type: web
    name: net360-preparation
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx vite preview --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        value: https://net360-api.onrender.com

  - type: web
    name: net360-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:server
    autoDeploy: true
    envVars:
      - key: API_PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
